### ISSUE TITLE
docs.nodebb.org link doesnt have any info

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/nodebb-plugin-link-preview#26]
https://community.nodebb.org/topic/18161/help/2

**Comment by julianlam** [comment]
I think that's actually ok insomuch that the site didn't provide any og:description data. Might be something we have to update in our MkDocs install actually.

**Comment by julianlam** [comment]
8ff7d7974b2f5a1a990f9755bdaa16dd4858c808

**Comment by julianlam** [comment]
nodebb/docs@8ff7d7974b2f5a1a990f9755bdaa16dd4858c808
